### ISSUE TITLE
Feature request: Change background

### ISSUE THREAD

**Issue by sp00ne** [allco/BottomSheetLib#4]
Hi there! Great library 👍 

I would like to be able to change the background of the bottom sheet in an easy manner, I'd guess the difficulty lies in the fact that the "actual" view of the bottom sheet is not the layout that you put on top but is actually something you have to fish out in your bottom sheet builder.

With changing background it could mean:
* Ability to set top corner radius 
* (Harder) to set the background drawable to a custom one

**Comment by allco** [comment]
Added 
```
    @DrawableRes
    var backgroundRes: Int? = null
    var backgroundDrawable: Drawable? = null
```
to BottomSheetSettings

The usage is:
```
    bottomSheet {
            backgroundRes = R.drawable.custom_bg
            // or
            // backgroundDrawable = AppCompatResources.getDrawable(view.context, R.drawable.custom_bg)
            ....
        }.show()
```

**Comment by allco** [comment]
https://github.com/allco/BottomSheetLib/tree/develop#5
